-
  name: add cache dir
  file:
    path: /opt/cache
    state: directory
-
  name: install nginx
  yum:
    name: nginx
    state: latest
  nofity: restart ngnix

handlers:
-
  name: restart ngnix
  service:
    name: ngnix
    state: restarted
