---
-
  name: apply the common configuration to all hosts
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    -common

-
  name: apply the DB config
  hosts: DBservers

  roles:
    - mariadb

-
  name: apply apache and web roles
  hosts: webservers

  roles:
    - apache
    - web

-
  name: apply the lb config
  hosts: lbservers

  roles:
    - haproxy

    
